name: Install pnpm and Node.js
runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      run: npm install -g pnpm@^8.3.1
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ^18.15.0
