# - name: Setup pnpm
#   uses: pnpm/action-setup@v2.2.4
#   with:
#     # Version of pnpm to install
#     version: '8.x'
#     # Where to store pnpm files
#     # dest: # optional, default is ~/setup-pnpm
#     # If specified, run `pnpm install`
#     run_install: # optional, default is null

name: build

on:
  pull_request:
    branches:
      - main

jobs:
  branch-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get base branch name
        id: get-base-branch-name
        run: |
          if [[ '${{github.event.pull_request.base.ref}}' != '' ]]; then
            echo 'branch=${{github.event.pull_request.base.ref}}' >> $GITHUB_OUTPUT
          else
            echo 'branch=main' >> $GITHUB_OUTPUT
          fi
      - name: Get branch name
        id: get-branch-name
        uses: tj-actions/branch-names@v7.0.1
    outputs:
      base-branch-name: ${{ steps.get-base-branch-name.outputs.branch }}
      branch-name: ${{ steps.get-branch-name.outputs.branch }}

  get-affected:
    needs: [branch-info]
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3.0.2
        with:
          main-branch-name: ${{needs.branch-info.outputs.base-branch-name}}
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: '8.x'
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Get affected
        id: get-projects-arrays
        run: |
          if [[ '${{github.event.pull_request.base.ref}}' == '' && '${{needs.branch-info.outputs.branch-name}}' == 'main' ]]; then
            echo 'test-unit=$(node scripts/print-affected-array.js test:unit --all)' >> $GITHUB_OUTPUT
            echo 'test-e2e=$(node scripts/print-affected-array.js test:e2e --all)' >> $GITHUB_OUTPUT
          else
            echo 'test-unit=$(node scripts/print-affected-array.js test:unit origin/${{needs.branch-info.outputs.base-branch-name}})' >> $GITHUB_OUTPUT
            echo 'test-e2e=$(node scripts/print-affected-array.js test:e2e origin/${{needs.branch-info.outputs.base-branch-name}})' >> $GITHUB_OUTPUT
          fi
    outputs:
      test-unit: ${{ steps.get-projects-arrays.outputs.test-unit }}
      test-e2e: ${{ steps.get-projects-arrays.outputs.test-e2e }}

  test-unit:
    runs-on: ubuntu-latest
    needs: [get-affected]
    # Skip the job if there are not affected projects containing unit tests
    steps:
      - name: Get workspaces
        id: get-workspaces
        if: ${{ fromJson(needs.get-affected.outputs.test-unit)[0] }}
        env:
          TEST_UNIT: ${{ needs.get-affected.outputs.test-unit }}
          TEST_E2E: ${{ needs.get-affected.outputs.test-e2e }}
        run: echo 'unit-test-array=$TEST_UNIT' >> $GITHUB_OUTPUT

      - name: Test result
        id: test-result
        run: 'echo $unit-test-array'

    outputs:
      unit-test-array: ${{ steps.get-workspaces.outputs.unit-test-array}}
