# This workflow will test the db package

name: Node.js CI DB Management

on:
  pull_request:
    branches:
      - main

jobs:
  branch-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get base branch name
        id: get-base-branch-name
        run: |
            if [[ "${{github.event.pull_request.base.ref}}" != "" ]]; then
              echo "::set-output name=branch::${{github.event.pull_request.base.ref}}"
            else
              echo "::set-output name=branch::main"
            fi
      - name: Get branch name
        id: get-branch-name
        uses: tj-actions/branch-names@v5.2
      
    outputs:
      base-branch-name: ${{ steps.get-base-branch-name.outputs.branch }}
      branch-name: ${{ steps.get-branch-name.outputs.branch }}
    
