name: Set up testing environment

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo HI and ${{ inputs.project-name }}'
